import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppProvider } from './LanguageContext';
import Header from "@/Components/Header/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "IT TIME ACADEMY - O'zbekistondagi Eng Zo'r Dasturlash Markazi | TOP IT O'quv Markazi",
  description: "Generated by create next app",
  icons: {
    icon: '/logo.png'
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProvider>
          <Header />
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
